export enum UniformTypeEnum
{
    FLOAT = "FLOAT",
    FLOAT_VEC2 = "FLOAT_VEC2",
    FLOAT_VEC3 = "FLOAT_VEC3",
    FLOAT_VEC4 = "FLOAT_VEC4",
    INT = "INT",
    BOOL = "BOOL",
    INT_VEC2 = "INT_VEC2",
    BOOL_VEC2 = "BOOL_VEC2",
    INT_VEC3 = "INT_VEC3",
    BOOL_VEC3 = "BOOL_VEC3",
    INT_VEC4 = "INT_VEC4",
    BOOL_VEC4 = "BOOL_VEC4",
    FLOAT_MAT2 = "FLOAT_MAT2",
    FLOAT_MAT3 = "FLOAT_MAT3",
    FLOAT_MAT4 = "FLOAT_MAT4",
    FLOAT_ARRAY = "FLOAT_ARRAY",
    BOOL_ARRAY = "BOOL_ARRAY",
    INT_ARRAY = "INT_ARRAY"
}
